// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0MQo21JiwiS4WK6kHDFnt-kK_Ky-iAJg',
    appId: '1:1017459134618:web:f1fa7b781f265209664f23',
    messagingSenderId: '1017459134618',
    projectId: 'video-content-curation-project',
    authDomain: 'video-content-curation-project.firebaseapp.com',
    databaseURL: 'https://video-content-curation-project-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'video-content-curation-project.appspot.com',
    measurementId: 'G-VJXF8HH6WG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8Ld6erKvaGFuSrzoTXGA09DraC1fbRCE',
    appId: '1:1017459134618:android:cc2217faf930f44a664f23',
    messagingSenderId: '1017459134618',
    projectId: 'video-content-curation-project',
    databaseURL: 'https://video-content-curation-project-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'video-content-curation-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCP7QDc78JwR8uuIkzkNfbB6A_Xoxh1nbM',
    appId: '1:1017459134618:ios:9d99895ed6eb2b0c664f23',
    messagingSenderId: '1017459134618',
    projectId: 'video-content-curation-project',
    databaseURL: 'https://video-content-curation-project-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'video-content-curation-project.appspot.com',
    iosClientId: '1017459134618-t5kutf5e8ctrpggsqeka4tt7idd1eq9g.apps.googleusercontent.com',
    iosBundleId: 'com.example.videoCurationAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCP7QDc78JwR8uuIkzkNfbB6A_Xoxh1nbM',
    appId: '1:1017459134618:ios:9d99895ed6eb2b0c664f23',
    messagingSenderId: '1017459134618',
    projectId: 'video-content-curation-project',
    databaseURL: 'https://video-content-curation-project-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'video-content-curation-project.appspot.com',
    iosClientId: '1017459134618-t5kutf5e8ctrpggsqeka4tt7idd1eq9g.apps.googleusercontent.com',
    iosBundleId: 'com.example.videoCurationAdmin',
  );
}
